modLoader="javafml"
loaderVersion="[45,)"
license="MIT"
[[mods]]
modId="noobland"
version="0.0.1-1.19.4"
displayName="Noob Land"
logoFile="noobland.png"
credits="Thanks to Kaupenjoe for his great tutorials"
description='''
Noob Land is the mod developped for the private Minecraft server called "Noob Land".
'''
[[dependencies.nooblland]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
